name: deepl
description:  An inofficial dart library that calls the DeepL API
version: 0.0.1-alpha
repository: https://github.com/hayribakici/deepl-dart

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  http: ^1.2.0
  json_annotation: ^4.8.1
  csv: ^6.0.0
  

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.4.6
  json_serializable: ">=6.7.1 <7.0.0"
  envied: ^0.5.4+1
  envied_generator: ^0.5.4+1
